### ISSUE TITLE
怎么请作者喝杯奶茶

### ISSUE THREAD

**Issue by zhangy2233** [GuoYaxiang/craftinginterpreters_zh#1]
有中文的, 让我可以摆脱机翻, 很感谢你

**Comment by GuoYaxiang** [comment]
共同学习（🤝）
我只是在学习的时候记录下来了，有不准确的地方还请多多指正。

**Comment by GuoYaxiang** [comment]
> 有中文的, 让我可以摆脱机翻, 很感谢你

共同学习（🤝）
我只是在学习的时候记录下来了，有不准确的地方还请多多指正。
