### ISSUE TITLE
文章很棒

### ISSUE THREAD

**Issue by FoooooooF** [GuoYaxiang/craftinginterpreters_zh#2]
中英对照的形式很好，有些中文没翻译到位的，可以直接查看英文，我本来也想翻译这篇文章，但是一直没有时间。如果需要人手，我可以帮忙翻译一些章节

**Comment by GuoYaxiang** [comment]
你说的很对，我采用中英对照的形式，就是担心有些语句或术语翻译出错干扰读者理解 : )。  
我在readme当中写了当前进展，你如果有时间的话，可以选择自己感兴趣的章节进行翻译，联系我在readme中进行标记即可，感谢你的帮助
