### ISSUE TITLE
希望可以帮忙一起翻译

### ISSUE THREAD

**Issue by hungrymegumin** [GuoYaxiang/craftinginterpreters_zh#3]
我最近刚发现这本书，看了前边一部分觉得很不错，目前在github上看到您好像是唯一还在坚持翻译的人，我对编译器和语言也比较感兴趣，也曾参与过英文书籍的翻译，请问是否需要帮忙？

**Comment by cache0928** [comment]
希望这个翻译还在继续。十分期待后续的章节

**Comment by lright1994** [comment]
我看了下这本书质量真的是很高，我也希望参与到翻译中，请问下作者有没有计划？

**Comment by GuoYaxiang** [comment]
我在readme当中记录了当前进展，你如果有时间的话，可以选择自己感兴趣的章节进行翻译。
先提一个issue领取章节，然后联系我在readme中进行标记即可。
