### ISSUE TITLE
建议在原作者仓库基础上修改，以便生成在线可读html版本

### ISSUE THREAD

**Issue by ycrao** [GuoYaxiang/craftinginterpreters_zh#4]
如题，原仓库作者提供生成html的工具，可以很方面的生成静态页面网站。搭配 `codespaces` 开发 预览效果如下：
<img width="831" alt="image" src="https://user-images.githubusercontent.com/3280204/170476055-df5145bc-863b-4379-af3c-d7d0f08a78de.png">

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/3280204/170476211-7ee879e7-d055-4c3f-8fe2-6ad41ce242fd.png">

**Comment by GuoYaxiang** [comment]
感谢反馈，我改天研究一下 :)

**Comment by ycrao** [comment]
我这里搞了 fork 原作者的仓库，改了一些构建代码以适配中文版：https://github.com/ycrao/craftinginterpreters-zh 可以参考一下。
为了节省时间，如果可以的话，前面十几章节可能考虑使用您目前已有的译文，转成 html 过程中也会做一些校对，后续剩余章节也可以分摊、协作翻译。

**Comment by GuoYaxiang** [comment]
> 我这里搞了 fork 原作者的仓库，改了一些构建代码以适配中文版：https://github.com/ycrao/craftinginterpreters-zh 可以参考一下。 为了节省时间，如果可以的话，前面十几章节可能考虑使用您目前已有的译文，转成 html 过程中也会做一些校对，后续剩余章节也可以分摊、协作翻译。

这个仓库本身就是为了帮助大家学习，我也觉得您这个形式更方便大家在PC端阅读，您可以使用我目前已提交的译文，但是需要满足两个条件：
1.在显著位置注明来源是GuoYaxiang，且附有这个仓库的地址  https://github.com/GuoYaxiang/craftinginterpreters_zh/。（翻译过程中确实很耗精力，尊重劳动成果哈 :））
2.不得用作商用。原作者已经刊印了实体书，尽管也保留了原本的Web页面，但是我们不能将译文内容用作商用。

PS：如果可以的话，尝试联系原作者为你提供一个友链，建议在原仓库中直接提issue。（我之前通过邮件联系过原作者未得到回复，大概是每天收到的消息太多了）

**Comment by wizardforcel** [comment]
看看 Docsify 吧，Markdown 直接在线渲染

https://docsify.js.org/#/zh-cn/

**Comment by hua-zhi-wan** [comment]
> 看看 Docsify 吧，Markdown 直接在线渲染
> 
> https://docsify.js.org/#/zh-cn/

🌿，原来已经有人提议过了。
