### ISSUE TITLE
在线展示

### ISSUE THREAD

**Issue by jh233wzb** [GuoYaxiang/craftinginterpreters_zh#41]
你好，请问有意愿做一个类似于gitbook的在线网站显示这些翻译内容吗，感觉这样会比较方便阅读些。

**Comment by GuoYaxiang** [comment]
感谢您的建议。
但是在本文翻译中，使用了一些typora的功能语法，在gitbook上展示可能会有问题。
不过，原仓库作者提供生成html的工具，可以很方面的生成静态页面网站。具体可以参考这个issue： #4 。
等全书内容翻译结束之后，我会考虑用这种形式生成一个更易阅读的可视化页面。

**Comment by GuoYaxiang** [comment]
当然，如果您有兴趣的话，也很鼓励您自己做一个可视化页面。就像我在另一个issue中评论的：

> 这个仓库本身就是为了帮助大家学习，我也觉得您这个形式更方便大家在PC端阅读，您可以使用我目前已提交的译文，但是需要满足两个条件：
1.在显著位置注明来源是GuoYaxiang，且附有这个仓库的地址 [https://github.com/GuoYaxiang/craftinginterpreters_zh/](https://github.com/GuoYaxiang/craftinginterpreters_zh) 。（翻译过程中确实很耗精力，尊重劳动成果哈）
2.不得用作商用。原作者已经刊印了实体书，尽管也保留了原本的Web页面，但是我们不能将译文内容用作商用。
