### ISSUE TITLE
craftinginterpreters_zh/content/4.扫描.md 

### ISSUE THREAD

**Issue by mannymu** [GuoYaxiang/craftinginterpreters_zh#53]
这个里面的  peek 函数的 ， 
  private char peek() {
    if (isAtEnd()) return '\0';
    return source.charAt(current);
  }

应该是 if (isAtEnd()) return '\n' ;  吗？

**Comment by GuoYaxiang** [comment]
不是的，\0表示空字符，在这里标识字符串结束；\n表示换行符，Lox程序中允许出现换行的，代码中也有对行数的处理
