### ISSUE TITLE
2.1.2节 It turns out human languages are too messy for the rigid grammars those parsers could handle, but they were a perfect fit for the simpler artificial grammars of programming languages. 

### ISSUE THREAD

**Issue by zhhqcoder** [GuoYaxiang/craftinginterpreters_zh#58]
原翻译为：事实证明，相对那些解析器能够处理的严格语法来说，人类语言太混乱了；但对于编程语言中更简单的人工语法来说，人类语言却是完美的。
个人感觉应该翻译为：事实证明，对于那些语法严格的解析器来说，人类语言太混乱了，但是对于处理那些语法简单的编程语言来说，他们是再合适不过的了。

**Comment by GuoYaxiang** [comment]
OK，后续会参考该意见进行处理

**Comment by LTstrange** [comment]
这句话是啥意思啊，英文中文都没看懂。。。

里面的they指代的是人类语言吗？还是严格语法的解析器啊。

- 如果是指代人类语言，那感觉怎么说都说不通。
- 如果是指代严格语法的解析器，那就能解释的通了：就是严格语法的解析器能够很好的解释语法简单的编程语言，而人类语言对于解析器来说太难、太复杂多变了。

**Comment by LTstrange** [comment]
要不我提个pull request改一下？ @GuoYaxiang

**Comment by GuoYaxiang** [comment]
已修正
