### ISSUE TITLE
第15章、16章中图片无法显示

### ISSUE THREAD

**Issue by huanguolin** [GuoYaxiang/craftinginterpreters_zh#6]
首先非常感谢作者的辛勤付出。让我等英语渣渣能比较便利的阅读这本书。
最近看到 15 章时发现图片无法显示。我看了下 markdown 中，使用了绝对路径。比如：
`(D:\翻译学习\CraftingInterpreters\15.虚拟机\ast-16511998979731.png)`
16章也是如此。
麻烦老兄修改一下。🙏
一键 replace 就好了。😄
如果需要的话我也可以提一个 pr.

**Comment by GuoYaxiang** [comment]
感谢反馈，那就麻烦您提交一个PR吧

**Comment by huanguolin** [comment]
> 感谢反馈，那就麻烦您提交一个PR吧

抱歉，看到比较晚。
我看你已经修复了，感谢🙏
