### ISSUE TITLE
11章节内parse和resolve都被译成了解析，有歧义

### ISSUE THREAD

**Issue by hua-zhi-wan** [GuoYaxiang/craftinginterpreters_zh#67]
eg:
> After the **parser** produces the syntax tree, but before the interpreter starts executing it, we’ll do a single walk over the tree to **resolve** all of the variables it contains.  
> 在**解析器**生成语法树之后，解释器执行语法树之前，我们会对语法树再进行一次遍历，以**解析**其中包含的变量。

parse一般指代对语法做解析，指通过token构建语法树的过程。而resolve指代的是类似“分析使用某物”的含义。

这里期待能用其他词汇替换一下，或者对于有歧义的位置对原有英文词汇予以保留。

（这种也算是中文的编译解释器相关内容的一个常见谬误了

**Comment by hua-zhi-wan** [comment]
可恶，草率了。原来12章声明了这个谬误（

**Comment by GuoYaxiang** [comment]
感谢您的意见
