### ISSUE TITLE
8轨音乐

### ISSUE THREAD

**Issue by wuqi** [GuoYaxiang/craftinginterpreters_zh#77]
3.9.1  第一段里面，  8轨音乐这玩意是说的磁带...

在中国大陆，通常“磁带”或者“录音带”一词都指[紧凑音频盒带](https://baike.baidu.com/item/%E7%B4%A7%E5%87%91%E9%9F%B3%E9%A2%91%E7%9B%92%E5%B8%A6/6117228?fromModule=lemma_inlink)，因为它的应用非常广泛。在中国[台湾](https://baike.baidu.com/item/%E5%8F%B0%E6%B9%BE/122340?fromModule=lemma_inlink)，[reel](https://baike.baidu.com/item/reel/9841217?fromModule=lemma_inlink)-to-reel tape被称为盘式录音带、紧凑音频盒带（Compact audio cassette）被称为[卡式录音带](https://baike.baidu.com/item/%E5%8D%A1%E5%BC%8F%E5%BD%95%E9%9F%B3%E5%B8%A6/499655?fromModule=lemma_inlink)、8轨软片（8-track cartridges)）被称为匣式录音带。

**Comment by GuoYaxiang** [comment]
感谢指教，我补充到脚注中
